server:
  port: 8080

stats-server:
  url: http://stats-server:9090

logging:
  level:
    root: INFO
    ru.practicum: INFO
    sun.rmi: INFO
    javax.management: INFO

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        check_nullability: true
        jdbc:
          time_zone: UTC
  datasource:
    url: jdbc:postgresql://ewm-db:5432/ewm-service
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

ru.practicum.client:
  server:
    host: stats-server
    port: 9090